spack:
  packages:
    all:
      compiler: [oneapi@2025.0.4]
  specs:
  - cmake%oneapi@2025.0.4
  - gmake%oneapi@2025.0.4
  - hdf5%oneapi@2025.0.4
  - netcdf-c%oneapi@2025.0.4+mpi+parallel-netcdf
  - netcdf-fortran%oneapi@2025.0.4
  - openmpi%oneapi@2025.0.4
  concretizer:
    unify: true
  config:
    install_missing_compilers: true
